blog/urls.py
from django.urls import path

from .feeds import LatestPostsFeed
from .views import post_api_details, post_api_list, post_detail,post_list,post_search, about
# from rest_framework.routers import DefaultRouter
# router = DefaultRouter()
# router.register('employs', )



app_name = 'blog'
urlpatterns = [

    path('', post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', post_list, name='post_list_by_tag'),

    path('<uuid:uuid>/',  post_detail, name='post_detail'),

    path('feed/', LatestPostsFeed(), name='post_feed'),

    path('search/', post_search, name='post_search'),
    path('about/', about, name='about'),


    #     api
    path('api/', post_api_list),
    path('api/<uuid:uuid>/', post_api_details),

    #     router
    # path('', include(router.urls)),

]

blog/models.py
import os
import uuid

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from taggit.managers import TaggableManager


def getFileName(filePath):
    base_name = os.path.basename(filePath)
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_image_path(instance, filename):
    new_file = uuid.uuid4()
    name, ext = getFileName(filename)
    final_name = '{newFile}{ext}'.format(newFile=new_file, ext=ext)
    return "blog/{newFile}{finalname}".format(newFile=new_file,
                                              finalname=final_name)


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,
                     self).get_queryset() \
            .filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    tags = TaggableManager()

    uuid = models.UUIDField(
        unique=True, default=uuid.uuid4, editable=False)

    title = models.CharField(max_length=400)
    slug = models.SlugField(max_length=450,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts')

    image = models.ImageField(upload_to=upload_image_path,
                              blank=True, null=True)

    description = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')
    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return str(self.uuid)

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       # args=[str(self.id)])
                       kwargs={'uuid': str(self.uuid)})

    @property
    def image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url

    # def get_absolute_url(self):
    #     return reverse('blog:post_detail',
    #                    args=[self.publish.year,
    #                          self.publish.month,
    #                          self.publish.day, self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blog/forms.py
from .models import Comment
from django import forms
from django_summernote.admin import SummernoteModelAdmin


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    query = forms.CharField()


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                         widget=forms.Textarea)

blog/views.py
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.core.paginator import Paginator, EmptyPage, \
    PageNotAnInteger
from django.db.models import Count
from django.shortcuts import render, get_object_or_404

#api
from rest_framework.response import Response
from rest_framework import status
from rest_framework.decorators import api_view

#local
from .serializers import PostSerializer
from .forms import CommentForm, SearchForm
from .models import Post
from taggit.models import Tag


def about(request):
    return render(request, 'about.html')


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 6)  # 6 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request,
                  'blog/list.html',
                  {'page': page,
                   'posts': posts,
                   'tag': tag})


# class PostListView(ListView):
#     queryset = Post.published.all()
#     context_object_name = 'posts'
#     paginate_by = 6
#     template_name = 'blog/list.html'


def post_detail(request, uuid):
    post = get_object_or_404(Post, uuid=uuid)

    # List of active comments for this post
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids) \
        .exclude(uuid=post.uuid)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')) \
                        .order_by('-same_tags', '-publish')[:4]

    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()
    return render(request,
                  'blog/detail.html',
                  {'post': post,
                   'comments': comments,
                   'new_comment': new_comment,
                   'comment_form': comment_form,
                   'similar_posts': similar_posts})


def post_search(request):
    search_form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        search_form = SearchForm(request.GET)
        if search_form.is_valid():
            query = search_form.cleaned_data['query']
            search_vector = SearchVector('title', 'description')
            search_query = SearchQuery(query)
            results = Post.published.annotate(
                search=search_vector,
                rank=SearchRank(search_vector, search_query)
            ).filter(search=search_query).order_by('-rank')

            # paginator = Paginator(request, results, 6)
    context = {
        'search_form': search_form,
        'query': query,
        'results': results
    }

    return render(request,
                  'blog/search.html', context)


@api_view(['GET'])
def post_api_list(request):
    if request.method == 'GET':
        emp = Post.objects.all()
        serializer = PostSerializer(emp, many=True)
        return Response(serializer.data)

    # elif request.method == 'POST':
    #     serializer = PostSerializer(data=request.data)
    #     if serializer.is_valid():
    #         serializer.save()
    #         return Response(serializer.data, status=status.HTTP_201_CREATED)
    #     return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

# @api_view(['GET', 'PUT', 'DELETE'])
@api_view(['GET'])
def post_api_details(request, uuid):
    try:
        post = Post.objects.get(uuid=uuid)
    except Post.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)
    if request.method == 'GET':
        serializer = PostSerializer(post)
        return Response(serializer.data)
    # elif request.method == 'PUT':
    #     serializer = PostSerializer(emp, data=request.data)
    #     if serializer.is_valid():
    #         serializer.save()
    #         return Response(serializer.data)
    #     return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    # elif request.method == 'DELETE':
    #     emp.delete()
    #     return Response(status= status.HTTP_204_NO_CONTENT)

templates/blog/detail.html
{% extends "base.html" %}
{% load blog_tags %}

{% with comments.count as total_comments %}
  <h2>
    {{ total_comments }} comment{{ total_comments|pluralize }}
  </h2>
{% endwith %}

{#{% block title %}{{ post.title }}{% endblock %}#}
{% block content %}

    <div class="container">
    <div class="row no-gutters page-grid">
  <h2 class="card-title">{{ post.title }}</h2>
        <hr align="LEFT" size="1" width="80%">

{#  <p class="date">#}
{#    Published {{ post.publish | safe }} by {{ post.author | safe }}#}
{#  </p>#}
  <h2 class="card-subtitle" >{{ post.description|markdown | safe }}</h2>
    </div>


{#    {% for comment in comments %}#}
{#  <div class="comment">#}
{#    <p class="info">#}
{#      Comment {{ forloop.counter }} by {{ comment.name }}#}
{#      {{ comment.created }}#}
{#    </p>#}
{#    {{ comment.body|linebreaks }}#}
{#  </div>#}
{#{% empty %}#}
{#  <p>There are no comments yet.</p>#}
{#{% endfor %}#}
{#    {% if new_comment %}#}
{#  <h2>Your comment has been added.</h2>#}
{#{% else %}#}
{#  <h2>Add a new comment</h2>#}
{#  <form method="post">#}
{#    {{ comment_form.as_p }}#}
{#    {% csrf_token %}#}
{#    <p><input type="submit" value="Add comment"></p>#}
{#  </form>#}
{#{% endif %}#}
        <hr align="CENTER" size="2" width="70%">

    <h2>Similar topics</h2>
{% for post in similar_posts %}
  <p>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
  </p>
{% empty %}
  There are no similar posts yet.
{% endfor %}
        </div>
{% endblock %}

templates/blog/example.html
{% extends "base.html" %}
{% block content %}

    <div class="container">
        <div class="row no-gutters page-grid">
            <div class="col">
                <hr>
                <div class="card-group">
                    {% for post in posts %}
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">
                              <a href="{{ post.get_absolute_url }}">
                                  {{ post.title }}
                              </a>
                            </h4>
                            <p class="card-text">
                                {{ post.description|truncatewords:30|linebreaks }}</p>
                            <p class="post-meta">
                                {{ post.publish|date }} by {{ post.author }}
                            </p>
                        </div>
                    </div>
                      {% endfor %}
                </div>
                <hr>


{#                <div class="col-lg-4">#}
{#<div class="section-title">#}
{#<h2>Trending</h2>#}
{#</div>#}

<div class="card-group">
{% for post in posts %}
<div class="card">
<div class="trend-entry d-flex">
<div class="card-body">
    <div class="number align-self-start">{{ post.publish|date:"d" }}</div>
<div class="number2">{{ post.publish|date:"N y" }}</div>
    <div class="trend-contents">
        <h4 class="card-title">
<a href="{{ post.get_absolute_url }}">
{{ post.title }}
</a></h4>
{#<div class="post-meta">#}
    <p class="card-text">
        {{ post.description|truncatewords:30|linebreaks }}</p>

{#<span class="d-block">#}
{#<span class="date-read">Jun <span class="mx-1">•#}
{#</span> min <span class="icon-star2"></span></span>#}
</div>
</div>
</div>
</div>
{#</div>#}

</div>
   {% endfor %}




                <div class="clearfix"><button class="btn btn-primary float-right" type="button" style="background: #4c280f;height: 37px;font-size: 14px;border-style: none;border-color: #4c280f;">Older Posts&nbsp;⇒</button></div>
            </div>
        </div>
    </div>

{% endblock %}

templates/blog/latest_posts.html
<ul>
  {% for post in latest_posts %}
    <li>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
  {% endfor %}
</ul>

templates/blog/list.html
{% extends "base.html" %}
{% load blog_tags %}
{% load static %}


{% block about %}

{% include "baseAbout.html"%}

{% endblock about %}


{% block content %}

    <div class="container">
    <div class="row no-gutters page-grid">
           {% for post in posts %}
        <div class="col-md-6 col-sm-6">
            <ul style="list-style: none;">
                <li>
                    <div style=" padding-top: 5px; margin-top: 50px;
                    background:
                    url({% static 'assets/img/border_diagonal.png' %})
                    repeat-x 0 top;">
                    </div>
                    <div class="trend-entry d-flex"  >
                        <div class="number align-self-start">{{ post.publish|date:"d" }}</div>
                        <br>
                        <div class="number2">{{ post.publish|date:"N y " }} </div>
                        <div class="port-title">
                        <h6 class="title" >
                            <a style="text-decoration:none; color:black" href="{{ post.get_absolute_url }}">
                              {{ post.title }}
                            </a>
                        </h6>
                             </div>
                    </div>
                    <hr>
                </li>
                <ul style="list-style: none;">
                    <li >
                        <p>{{ post.description|markdown|truncatewords_html:30 | safe }}</p>
                    </li>

                <li>
                    <p class="tags">
                    {% for tag in post.tags.all %}
                    <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                    #{{ tag.name }}
                    </a>
                    {% if not forloop.last %}, {% endif %}
                    {% endfor %}
                    </p>
                </li>
            </ul>

              </ul>
        </div>
           {% endfor %}
        <hr />


    </div>
                <div class="clearfix">
{#          {% include "blog/pageination.html" with page=page_obj %}#}
            {% include "blog/pageination.html" with page=posts %}

        </div>



</div>


{% endblock %}

templates/blog/listexample.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <div class="row no-gutters page-grid">
            <div class="col">
                <hr>
                <ul>
                    {% for post in posts %}
                        <div class="trend-entry d-flex">
                            <div class="number align-self-start">{{ post.publish|date:"d" }}</div>
                            <div class="number2">{{ post.publish|date:"N y" }}</div>
                            <div class="trend-contents">
                                <h4 class="card-title">
                                    <a href="{{ post.get_absolute_url }}">
                                        {{ post.title }}
                                    </a>
                                </h4>
                                <p class="card-text">
                                    {{ post.description|truncatewords:30|linebreaks }}</p>
                            </div>
                        </div>
                    {% endfor %}
                </ul>
                <hr>
                <div class="clearfix"><button class="btn btn-primary float-right" type="button" style="background: #4c280f;height: 37px;font-size: 14px;border-style: none;border-color: #4c280f;">Older Posts&nbsp;⇒</button></div>
            </div>
        </div>
    </div>
{% endblock %}

templates/blog/pageination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current">
      Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
    {% if page.has_next %}
      <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
  </span>
</div>

templates/blog/search.html
  {% if query %}
    <h1>Posts containing "{{ query }}"</h1>
    <h3>
      {% with results.count as total_results %}
          Found {{ total_results }} result{{ total_results|pluralize }}
      {% endwith %}
    </h3>
    {% for post in results %}
        <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
        {{ post.description|markdown|truncatewords_html:5 }}
    {% empty %}
      <p>There are no results for your query.</p>
    {% endfor %}
{#    <p><a href="{% url "blog:post_search" %}">Search again</a></p>#}
{#  {% else %}#}
{#    <h1>Search for posts</h1>#}
{#    <form method="get">#}
{#      {{ search_form.as_p }}#}
{#      <input type="submit" value="Search">#}
{#    </form>#}
  {% endif %}