blog/urls.py
from django.urls import path

from .feeds import LatestPostsFeed
from .views import post_api_details, post_api_list, post_detail,post_list,post_search, about
# from rest_framework.routers import DefaultRouter
# router = DefaultRouter()
# router.register('employs', )



app_name = 'blog'
urlpatterns = [

    path('', post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', post_list, name='post_list_by_tag'),

    path('<uuid:uuid>/',  post_detail, name='post_detail'),

    path('feed/', LatestPostsFeed(), name='post_feed'),

    path('search/', post_search, name='post_search'),
    path('about/', about, name='about'),


    #     api
    path('api/', post_api_list),
    path('api/<uuid:uuid>/', post_api_details),

    #     router
    # path('', include(router.urls)),

]

contact/urls.py
from django.urls import path

from .views import contactView, successView, resumeView

app_name = 'contact'

urlpatterns = [
    path('', contactView, name='contact'),
    path('success/', successView, name='success'),
    path('resume/', resumeView, name='resume'),

]

templates/about.html
{% extends "base.html" %}
{% load blog_tags %}

{% block about %}

 <div class="about">
{#    <div class="row no-gutters page-grid">#}
        <p>
            My name is Anwar, and at the moment, I live in New York. I am interested in modern applications that serve various
            purposes in automating business and end-user processes.
        </p>
        <p>
            I have a passion for designing, developing, maintaining, testing and evaluating software.
            I am currently working on my other websites/applications that interact with smart contracts and ML/DL algorithms;
            however, I am also looking for a full-time job.
{#            What do you think about this site? Actually, no need to think about it, because I didn't even try my hardest. #}
{#            I enjoy developing and writing things when I have time.#}
        </p>
     <p>
{#         Back in 2009, I used the ASP/VBScript languages in this domain. #}
         Here is my <a href="{% url 'blog:post_list' %}">blog</a>, which will cover most of the tools that I mentioned on my
         <a href="{% url 'contact:resume' %}">resume</a>, bigly! I've developed the front-end and back-end of this website as well as hosting
         it in an EC2 instance; although it is still in development.
        </p>
        <p>
            Since 2005 I have enjoyed mentoring teachers, employees, graduate, and undergraduate students in technology-related topics.
            If you're looking for an experienced mentor in this field, please don't hesitate to <a href="{% url 'contact:contact' %}">contact</a> me.
        </p>
                <hr align="LEFT" size="1" width="70%">

        <br>

{#        <hr align="left" size="2" width="30%">#}

        <div class="section-title">

        <br>
        <b>If you have a job offer:</b>
        <br>I appreciate informal conversations, strategy discussions, and exchange of experiences. I expect to work with straightforward clients, prepared interviewers, and clients who are committed to the date of the interviews.
            <br><b>Benefits:</b>
        <br>I am looking for the following:
        <br>Stock-options or possible bonuses,
        <br>Excellent health plan,
        <br>Flexible vacation policy,
        <br>Budget for conference speaking, attendance, and travel.

        <br><br>I am not concerned with:
        <br>Free food or snacks in the office,
        <br>Weekly staff parties or vacation trips

        </div>
        <hr align="CENTER" size="1" width="70%">


    </div>
{# </div>#}
{% endblock about %}

templates/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Anwar site</title>
    <meta name="description" content="anwar's blog">
    <link rel="icon" href="{% static "assets/ico/favicon.ico" %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static "assets/bootstrap/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static  "assets/fonts/ionicons.min.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/Corporate-Footer-Clean.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/Footer-Clean.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/styles.css" %}">
</head>

<body>
    <nav class="navbar navbar-dark navbar-expand-md fixed-top bg-dark">
        <div class="container"><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="nav navbar-nav flex-grow-1 justify-content-between">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "blog:post_list" %}">
                            <div class="avatar"
                                 style="background:
                                 url({% static '/assets/img/download.png'%})
                            center / cover no-repeat;
                            margin: -9px;">
                            </div>
                        </a>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'blog:about' %}">About</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'contact:contact' %}">Contract</a></li>
                </ul>
            </div>
        </div>
    </nav>

<section class="portfolio-block block-intro" style="border-bottom-style: none;border-bottom-color: #9bafc4;">
        <div class="container ">
            <div class="text-md-left" >
             <div id="about">
                {% block about %}

                {% endblock about %}
             </div>
            </div>
        </div>
</section>


    <div id="content">
    {% block content %}

    {% endblock content %}
    </div>



    <div class="footer-clean">
        <footer>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-sm-4 col-md-3 item">
                        <h3>Home</h3>
                        <ul>
                            <li><a href="{% url "blog:post_list" %}">Blog</a>

                            </li>
{#                            <li><a href="#">Development</a></li>#}
{#                            <li><a href="#">Hosting</a></li>#}
                        </ul>
                    </div>
                    <div class="col-sm-4 col-md-3 item">
                        <h3>About</h3>
                        <ul>
                           <li><a class="nav-link" href="{% url 'blog:about' %}">Me</a></li>
{#                            <li><a href="#">Team</a></li>#}
{#                            <li><a href="#">Legacy</a></li>#}
                        </ul>
                    </div>
                    <div class="col-sm-4 col-md-3 item">
                        <h3>Contact</h3>
                        <ul>
                        <a class="nav-link" href="{% url 'contact:contact' %}">Me</a></li>
{#                            <li><a href="#">Employee success</a></li>#}
{#                            <li><a href="#">Benefits</a></li>#}
                        </ul>
                    </div>
                    <div class="col-lg-3 item social">
{#                        <a href="#">#}
{#                            <i class="icon ion-social-facebook"></i></a>#}
{#                        <a href="#">#}
{#                            <i class="icon ion-social-twitter"></i></a>#}
{#                        <a href="#">#}
{#                            <i class="icon ion-social-snapchat"></i></a>#}
{#                        <a href="#">#}
{#                            <i class="icon ion-social-instagram"></i></a>#}
                        <p class="copyright">Anwar © 2020</p>
                            <p>
                            <a class="small" href="{% url "blog:post_feed" %}">RSS</a>
                            </p>
                    </div>
                </div>
            </div>
        </footer>
    </div>
    <script src="{% static "assets/js/jquery.min.js" %}"></script>
    <script src="{% static "assets/bootstrap/js/bootstrap.min.js"%}"></script>
</body>

</html>

templates/baseAbout.html
{##}
{#<section class="portfolio-block block-intro">#}
{#    <div class="container">#}
        <div class="about-me">
        Hello there, my name is Anwar, and at the moment, I live in New York. I am interested in modern applications that serve various purposes
        <a href="{% url 'blog:about' %}"><strong>read more</strong></a>
        </div>
{#    </div>#}
{#</section>#}

templates/index.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Anwar -</title>
    <meta name="description" content="anwar's blog">
    <link rel="stylesheet" href="static/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="static/assets/fonts/ionicons.min.css">
    <link rel="stylesheet" href="static/assets/css/Corporate-Footer-Clean.css">
    <link rel="stylesheet" href="static/assets/css/Footer-Clean.css">
    <link rel="stylesheet" href="static/assets/css/styles.css">
</head>

<body>
    <nav class="navbar navbar-dark navbar-expand-md fixed-top bg-dark">
        <div class="container"><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="nav navbar-nav flex-grow-1 justify-content-between">
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <div class="avatar" style="background: url(&quot;assets/img/download.png&quot;) center / cover no-repeat;margin: -9px;padding: 0;padding-top: 0;padding-right: 0;padding-bottom: 0;padding-left: 0;"></div>
                        </a>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="#">Services</a></li>
                    <li class="nav-item"><a class="nav-link" href="#">Team</a></li>
                    <li class="nav-item"><a class="nav-link" href="#"><strong>contract</strong></a></li>
                </ul>
            </div>
        </div>
    </nav>
    <section class="portfolio-block block-intro" style="border-bottom-style: none;border-bottom-color: #9bafc4;">
        <div class="container">
{#            <div class="about-me">#}
{#                <p>Hello! I am <strong>Anwar</strong></p>#}
{#            </div>#}
        </div>
    </section>
    <div class="container">
        <div class="row no-gutters page-grid">
            <div class="col">
                <hr>
                <div class="card-group">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Title</h4>
                            <p class="card-text">Nullam id dolor id nibh ultricies vehicula ut id elit. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus.</p>
                            <p class="post-meta">Posted by&nbsp;<a href="#" style="border-color: #4c280f;">Start Bootstrap on July 8, 2018</a></p>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Title</h4>
                            <p class="card-text">Nullam id dolor id nibh ultricies vehicula ut id elit. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus.</p>
                            <p class="post-meta">Posted by&nbsp;<a href="#">Start Bootstrap on July 8, 2018</a></p>
                        </div>
                    </div>
                </div>
                <hr>
                <div class="clearfix"><button class="btn btn-primary float-right" type="button" style="background: #4c280f;height: 37px;font-size: 14px;border-style: none;border-color: #4c280f;">Older Posts&nbsp;⇒</button></div>
            </div>
        </div>
    </div>
    <div class="footer-clean">
        <footer>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-sm-4 col-md-3 item">
                        <h3>Services</h3>
                        <ul>
                            <li><a href="#">Web design</a></li>
                            <li><a href="#">Development</a></li>
                            <li><a href="#">Hosting</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-4 col-md-3 item">
                        <h3>About</h3>
                        <ul>
                            <li><a href="#">Company</a></li>
                            <li><a href="#">Team</a></li>
                            <li><a href="#">Legacy</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-4 col-md-3 item">
                        <h3>Careers</h3>
                        <ul>
                            <li><a href="#">Job openings</a></li>
                            <li><a href="#">Employee success</a></li>
                            <li><a href="#">Benefits</a></li>
                        </ul>
                    </div>
                    <div class="col-lg-3 item social"><a href="#"><i class="icon ion-social-facebook"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-instagram"></i></a>
                        <p class="copyright">Company Name © 2017</p>
                    </div>
                </div>
            </div>
        </footer>
    </div>
    <script src="static/assets/js/jquery.min.js"></script>
    <script src="static/assets/bootstrap/js/bootstrap.min.js"></script>
</body>

</html>